[tool.poetry]
name = "pydriver"
version = "0.1.0"
description = "Download selenium WebDriver for Windows, Mac & Linux"
authors = ["Krzysztof Czeronko <krzysztof.czeronko@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
pydriver = 'pydriver.pydriver:main'


[tool.poetry.dependencies]
python = "^3.6"
fire = "^0.2.1"
requests-html = "^0.10.0"
packaging = "^20.1"
humanfriendly = "^6.1"
configobj = "^5.0.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.4.4"
black = "^19.10b0"
changelog-cli = "^0.7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
