name: Create release and push to pypi

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.15]

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
        cache-dependency-path: 'poetry.lock'
    - name: Build wheel
      run: poetry build
    - name: Create github release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/pydriver-*.whl
        body_path: CHANGELOG.md
    - name: Upload built app to pypi
      env:
        USERNAME: ${{ secrets.PYPI_USERNAME}}
        PASSWORD: ${{ secrets.PYPI_PASSWORD}}
      run: poetry publish -u "$USERNAME" -p "$PASSWORD" -n
